application: hfzkdebug
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /intf/(call|sep)
  script: intf_\1.app

- url: /intf/(sina|facebook|twitter)/.*
  script: intf_\1.app

- url: /intf/smart
  script: intf_smart.app

- url: /user/.*
  script: user.app

- url: /account/.*
  script: account.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.3"
